### ISSUE TITLE
add additional context activity representing the CMS page that the content exists on

### ISSUE THREAD

**Issue by garemoko** [tunapanda/wp-h5p-xapi#1]
See https://github.com/h5p/h5p-php-library/issues/3

**Comment by garemoko** [comment]
I think this can be solved by capturing the post/page id [here](https://github.com/tunapanda/wp-h5p-xapi/blob/master/wp-h5p-xapi.php#L31) as a variable, then adding it to the statement [here](https://github.com/tunapanda/wp-h5p-xapi/blob/master/wp-h5p-xapi.js#L78).

Would you appreciate a PR implementing this?

**Comment by ceciliaTunapanda** [comment]
That sounds like a nice addition for the plugin. Go ahead and send a PR.

**Comment by limikael** [comment]
I think it sounds like a good idea as well!

I'm wondering if there is any value in making it optional so this functionality can be turned on and off on the settings page? Maybe I'm overthinking it....

**Comment by garemoko** [comment]
What would be the benefit of having it as an optional setting? 

Disadvantages:
1. More complex UI
2. People might turn it off without realising what it is
3. Inconsistency of statements from different H5P installations

**Comment by limikael** [comment]
Good point @garemoko, maybe the only point would be to make the admin page look more hi-tech and thereby boosting my ego? In that case it is probably best left out...

However, I'm also thinking that there might be situations where you would want the data "pure" as it comes from H5P, or situations where it would somehow interfere with other data? But if such a situation would show up we could always make it optional at that point. Sounds like a good way to start would be to just put it in there for all statements.

**Comment by garemoko** [comment]
The contextActivities properties contain arrays so adding this data doesn't remove any other data and shouldn't interfere. This is one reason why I'm suggesting putting it as a grouping though as parent is used by H5P in some places and it's good not to have more than one parent. I'll go ahead and not make it optional.

**Comment by limikael** [comment]
Merged and published in the wordpress plugin repo as version 0.0.2

Thanks alot @garemoko !
