### ISSUE TITLE
WordPress.org version of plugin isn’t being updated

### ISSUE THREAD

**Issue by SteelWagstaff** [tunapanda/wp-h5p-xapi#12]
Hi @limikael and @Jakeii 

We’ve noticed a bug in the WP [H5P xAPI plugin](https://wordpress.org/plugins/wp-h5p-xapi/) (version 0.1.6), which hard-coded a location for certain core WordPress files in a way that is discouraged. While the plugin there has not seen an update on WordPress.org in over a year, the master branch on GitHub includes more recent changes which should fix this bug. Would you be willing/open to updating the WP.org version of the plugin or should we update our installation stack to point to the code repo here on GitHub?

**Comment by Jakeii** [comment]
Hi @SteelWagstaff 
I did the last few fixes, however I didn't have the wordpress.org login, I've now got it and have updated the Wordpress repo, so it's now up to date.
