### ISSUE TITLE
Notice: Undefined variable: s in

### ISSUE THREAD

**Issue by tonygil** [tunapanda/wp-h5p-xapi#7]
Hi I am not sure what is causing this error

 Notice: Undefined variable: s in /home/giltedge/public_html/testlearndash/wp-content/plugins/wp-h5p-xapi/wp-h5p-xapi.php on line 24

Can you help ?
Tony

**Comment by limikael** [comment]
Ah... Checking the code there, it looks like:

```
	$s.="<script>\n";
```

And the `$s` variable is not declared. It should be declared and empty, so a line like this:

```
    $s="";
```

Just above that line should do the trick.

@c3c1l1a do you think you could try to explain this to the Tunapanda guys, and see if someone wants to take a stab at it?

**Comment by tonygil** [comment]
Thanks, will check and see what i can do

**Comment by limikael** [comment]
Thanks @tonygil! If you fix it, a PR would be well received!

**Comment by limikael** [comment]
Fixed and uploaded to the WordPress repo as version 0.1.6
