### ISSUE TITLE
Message: Credentials invalid for this endpoint.

### ISSUE THREAD

**Issue by ericbarns** [tunapanda/wp-h5p-xapi#8]
Re: Wordpress 4 and scormcloud LRS
Unable to save result data.

Message: Credentials invalid for this endpoint.
Code: 401

What do you mean as user name (my login usert name? or activity provider name)
What do you mean by password (my login password or the Key or Secrete
What do you mean by endpoint? this  https://cloud.scorm.com/tc/NKEJGA0L06/

It just dosent work, what ever i try, there are no examples of people using it on youtube or google!

Please advise

Regards

**Comment by garemoko** [comment]
user name = key
password = secret
endpoint = https://cloud.scorm.com/tc/NKEJGA0L06/

**Comment by ericbarns** [comment]
Anedrew Thanks
I have no idea why its just started to work, but thats good.We tracking interactive video, with simple multiple questions, so a bit a of data being sent.How can we tailor what data to pull back in for reporting?
Thanks for all your helpEric
 uk.linkedin.com/in/ebarns/

**Comment by limikael** [comment]
Good to hear that you got it working @ericbarns!

You are right when you say that there are not that many examples or videos on how to set it up. Now that you eventually got it working, maybe you would consider creating a video or an article explaining how you did it? If you would do that, we would be happy to put a link to the video or article from the settings page in the plugin and give credit where credit is due.

**Comment by limikael** [comment]
@ericbarns sorry, just realized there was a question there too...

To tailor which data that should actually be sent, there is the WordPress filter `h5p-xapi-pre-save`. You have the chance in that filter to modify the statement, or prevent it completely from being saved.

Does that make sense?

**Comment by ericbarns** [comment]
Yes I would be willing to develop a video and or audio visual presentation of using your plugin. However need help reading back data sent via your plugin after a interactive video and it's questions have finished, do you have any ideas how?
Look forward to working with you.Eric Barns

Sent from Yahoo Mail on Android 
 
  On Tue, 29 Nov, 2016 at 18:39, Mikael Lindqvist<notifications@github.com> wrote:   
Good to hear that you got it working @ericbarns!

You are right when you say that there are not that many examples or videos on how to set it up. Now that you eventually got it working, maybe you would consider creating a video or an article explaining how you did it? If you would do that, we would be happy to put a link to the video or article from the settings page in the plugin and give credit where credit is due.

**Comment by limikael** [comment]
@ericbarns Cool!

Yep we have some ideas on how to read the data back... This is not specific to our plugin, you read the data back in the same way as you would read from any xAPI endpoint...

You can use the TinCanPHP library for this:

https://github.com/RusticiSoftware/TinCanPHP

I have done that successfully.

However, I find that library to be a bit "bloated", so for our [Swag](http://swag.tunapanda.org/) project I developed a very tiny and lightweight thing that can fetch statements from an xAPI endpoint, but not much more:

https://github.com/tunapanda/wp-swag/blob/master/src/utils/Xapi.php

Here is an example of its usage:

https://github.com/tunapanda/wp-swag/blob/master/src/model/Swagpath.php#L181

I also created a very small utility in NodeJS which can export information from xAPI as a CSV file for inclusion in a spreadsheet:

https://github.com/tunapanda/xapireport

We are also working on a more comprehensive web based xAPI reporting tool, but that is very early work in progress.

Let me know if you want to collaborate on that! Also let me know if this answer was helpful. And let me take the opportunity to say that we can certainly provide more detailed and practical help on a consultant basis.

**Comment by ericbarns** [comment]
Mikael
Soz lat response. How can i help you, you mentioned video, any specific you would like to covered. I thought it might be good to go from the start and what to do if you encountered problems like i did and also how to pull data back form LRS. So essentially the very basic of installing, using you plugin and also requesting data back. But i could of course do more if you like whilst in the process, just let me know you ideas.
Will try out all of your suggestions, as i am keen to demonstrate both these two plugins and the advantages they can give to the L&D communinity here at Skills2learn and Babcock but the wider community at elearning hero's .
Kind RegardsEric BArns uk.linkedin.com/in/ebarns/

**Comment by limikael** [comment]
Hi Eric! Sorry for the late reply. I think the best would be if we talked about this, we can have a Skype session? I think there could be many areas where we could collaborate potentially. We are also working on an LRS as a wordpress plugin, but it is not released yet: http://github.com/tunapanda/wp-xapi-lrs

I added you on LinkedIn, we can continue the discussion there!
